<a href="https://colab.research.google.com/github/dharma610/Project/blob/master/Untitled7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
from scipy.integrate import odeint
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline 
!pip install mpld3
import mpld3
mpld3.enable_notebook()

Requirement already satisfied: mpld3 in /usr/local/lib/python3.6/dist-packages (0.5.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.6/dist-packages (from mpld3) (2.11.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.6/dist-packages (from mpld3) (3.2.2)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.6/dist-packages (from jinja2->mpld3) (1.1.1)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib->mpld3) (2.8.1)
Requirement already satisfied: numpy>=1.11 in /usr/local/lib/python3.6/dist-packages (from matplotlib->mpld3) (1.18.5)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.6/dist-packages (from matplotlib->mpld3) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib->mpld3) (1.2.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib->mpld3) (2.4.7)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.6/dist-packages (from python-dateutil>=2.1->matplotlib->mpld3) (1.12.0)

In [25]:
def deriv(y, t, N, beta, gamma):
    S, I, R = y
    dSdt = -beta * S * I / N
    dIdt = beta * S * I / N - gamma * I
    dRdt = gamma * I
    return dSdt, dIdt, dRdt

In [26]:
def plotsir(t, S, I, R):
  f, ax = plt.subplots(1,1,figsize=(10,4))
  ax.plot(t, S, 'b', alpha=0.7, linewidth=2, label='Susceptible')
  ax.plot(t, I, 'y', alpha=0.7, linewidth=2, label='Infected')
  ax.plot(t, R, 'g', alpha=0.7, linewidth=2, label='Recovered')

  ax.set_xlabel('Time (days)')

  ax.yaxis.set_tick_params(length=0)
  ax.xaxis.set_tick_params(length=0)
  ax.grid(b=True, which='major', c='w', lw=2, ls='-')
  legend = ax.legend()
  legend.get_frame().set_alpha(0.5)
  for spine in ('top', 'right', 'bottom', 'left'):
      ax.spines[spine].set_visible(False)
  plt.show();

In [27]:
import random
gamma = []
for i in range(1000):
    gamma.append(random.uniform(0, 1))

In [28]:
beta = []
for i in range(1000):
  beta.append(2*gamma[i])  #Parameters can be seen as list beta and gamma

In [29]:
P = []
Q = []
M  = []
for i in range(1000): #Plotted for 2 sets
  N = 1000
  S0, I0, R0 = 999, 1, 0  # initial conditions: one infected, rest susceptible
  t = np.linspace(0, 99, 100) # Grid of time points (in days)
  y0 = S0, I0, R0 # Initial conditions vector
  # Integrate the SIR equations over the time grid, t.
  ret = odeint(deriv, y0, t, args=(N, beta[i], gamma[i]))
  S, I, R = ret.T
  P.append(S)
  Q.append(I)
  M.append(R)

In [30]:
import pandas as pd

In [31]:
S_value = pd.DataFrame(P)
S_value.to_csv("Susceptible.csv")

In [32]:
I_value = pd.DataFrame(Q)
I_value.to_csv("Infected.csv")

In [33]:
R_value = pd.DataFrame(M)
R_value.to_csv("Recovered.csv")

In [34]:
S_value

        0           1           2   ...          97          98          99
0    999.0  998.994581  998.989148  ...  998.400044  998.393006  998.385949
1    999.0  996.367164  990.323929  ...  202.845900  202.845900  202.845900
2    999.0  996.946583  992.810810  ...  202.845900  202.845900  202.845900
3    999.0  996.987362  992.973760  ...  202.845900  202.845900  202.845900
4    999.0  996.442872  990.666976  ...  202.845900  202.845900  202.845900
..     ...         ...         ...  ...         ...         ...         ...
995  999.0  997.424169  994.618607  ...  202.845900  202.845900  202.845900
996  999.0  998.502555  997.881964  ...  202.889567  202.884160  202.879423
997  999.0  995.720817  987.176584  ...  202.845900  202.845900  202.845900
998  999.0  998.640017  998.215512  ...  203.994740  203.886900  203.789191
999  999.0  996.364452  990.311538  ...  202.845900  202.845900  202.845900

[1000 rows x 100 columns]

In [35]:
df1 = pd.concat([S_value, S_value[[2,6,9,27,37,43,56,79,90,95]].T.stack().reset_index(name='new')['new']], axis=1)

In [74]:
Df1 = pd.concat([S_value, S_value[[3,7,10,28,38,44,57,80,91,96]].T.stack().reset_index(name='new')['new']], axis=1)

In [36]:
df1["new"].head(1001)

0       998.989148
1       990.323929
2       992.810810
3       992.973760
4       990.666976
           ...
996     997.881964
997     987.176584
998     998.215512
999     990.311538
1000    998.967267
Name: new, Length: 1001, dtype: float64

In [37]:
df2 = pd.concat([I_value, I_value[[2,6,9,27,37,43,56,79,90,95]].T.stack().reset_index(name='new')['new']], axis=1)

In [75]:
Df2 = pd.concat([I_value, I_value[[3,7,10,28,38,44,57,80,91,96]].T.stack().reset_index(name='new')['new']], axis=1)

In [38]:
df2["new"]

0       1.005421e+00
1       5.314727e+00
2       4.081862e+00
3       4.000970e+00
4       5.144849e+00
            ...
9995   -3.636757e-10
9996    8.330995e-02
9997   -3.176822e-11
9998    2.037921e+00
9999   -4.669248e-11
Name: new, Length: 10000, dtype: float64

In [20]:
df3 = pd.concat([R_value, R_value[[2,6,9,27,37,43,56,79,90,95]].T.stack().reset_index(name='new')['new']], axis=1)

In [76]:
Df3 = pd.concat([R_value, R_value[[3,7,10,28,38,44,57,80,91,96]].T.stack().reset_index(name='new')['new']], axis=1)

In [39]:
df3["new"]

0         0.116476
1         4.103063
2         5.580720
3         2.384729
4         2.544825
           ...
9995    797.154100
9996    797.154100
9997    797.154100
9998      2.129711
9999    797.154100
Name: new, Length: 10000, dtype: float64

In [45]:
data = pd.DataFrame(df1["new"])

In [46]:
data["new"]

0       998.989148
1       990.323929
2       992.810810
3       992.973760
4       990.666976
           ...
9995    202.845900
9996    202.902783
9997    202.845900
9998    204.245126
9999    202.845900
Name: new, Length: 10000, dtype: float64

In [47]:
data["suspectible"] = data["new"]

In [48]:
data["infected"] = df2["new"]

In [49]:
data["recovered"] = df3["new"]

In [52]:
data.drop("new",axis = 1,inplace = True)

In [53]:
data

      suspectible      infected   recovered
0      998.989148  1.005421e+00    0.116476
1      990.323929  5.314727e+00    4.103063
2      992.810810  4.081862e+00    5.580720
3      992.973760  4.000970e+00    2.384729
4      990.666976  5.144849e+00    2.544825
...           ...           ...         ...
9995   202.845900 -3.636757e-10  797.154100
9996   202.902783  8.330995e-02  797.154100
9997   202.845900 -3.176822e-11  797.154100
9998   204.245126  2.037921e+00    2.129711
9999   202.845900 -4.669248e-11  797.154100

[10000 rows x 3 columns]

In [56]:
df4 = pd.DataFrame(beta)

In [69]:
df5 = pd.DataFrame(gamma)

In [59]:
df4[0]

0      0.005417
1      1.684596
2      1.416169
3      1.395865
4      1.651481
         ...
995    1.164509
996    0.444847
997    1.947224
998    0.331433
999    1.685772
Name: 0, Length: 1000, dtype: float64

In [62]:
df4[1] = df4[0]
df4[2] = df4[0]
df4[3] = df4[0]
df4[4] = df4[0]
df4[5] = df4[0]
df4[6] = df4[0]
df4[7] = df4[0]
df4[8] = df4[0]
df4[9] = df4[0]

In [70]:
df5[1] = df5[0]
df5[2] = df5[0]
df5[3] = df5[0]
df5[4] = df5[0]
df5[5] = df5[0]
df5[6] = df5[0]
df5[7] = df5[0]
df5[8] = df5[0]
df5[9] = df5[0]

In [63]:
df4

            0         1         2  ...         7         8         9
0    0.005417  0.005417  0.005417  ...  0.005417  0.005417  0.005417
1    1.684596  1.684596  1.684596  ...  1.684596  1.684596  1.684596
2    1.416169  1.416169  1.416169  ...  1.416169  1.416169  1.416169
3    1.395865  1.395865  1.395865  ...  1.395865  1.395865  1.395865
4    1.651481  1.651481  1.651481  ...  1.651481  1.651481  1.651481
..        ...       ...       ...  ...       ...       ...       ...
995  1.164509  1.164509  1.164509  ...  1.164509  1.164509  1.164509
996  0.444847  0.444847  0.444847  ...  0.444847  0.444847  0.444847
997  1.947224  1.947224  1.947224  ...  1.947224  1.947224  1.947224
998  0.331433  0.331433  0.331433  ...  0.331433  0.331433  0.331433
999  1.685772  1.685772  1.685772  ...  1.685772  1.685772  1.685772

[1000 rows x 10 columns]

In [64]:
df4 = pd.concat([df4, df4.T.stack().reset_index(name='new')['new']], axis=1)

In [71]:
df5 = pd.concat([df5, df5.T.stack().reset_index(name='new')['new']], axis=1)

In [66]:
data["beta"] = df4["new"]

In [72]:
data["gamma"] = df5["new"]

In [73]:
data

      suspectible      infected   recovered      beta     gamma
0      998.989148  1.005421e+00    0.116476  0.005417  0.002708
1      990.323929  5.314727e+00    4.103063  1.684596  0.842298
2      992.810810  4.081862e+00    5.580720  1.416169  0.708085
3      992.973760  4.000970e+00    2.384729  1.395865  0.697932
4      990.666976  5.144849e+00    2.544825  1.651481  0.825741
...           ...           ...         ...       ...       ...
9995   202.845900 -3.636757e-10  797.154100  1.164509  0.582255
9996   202.902783  8.330995e-02  797.154100  0.444847  0.222423
9997   202.845900 -3.176822e-11  797.154100  1.947224  0.973612
9998   204.245126  2.037921e+00    2.129711  0.331433  0.165716
9999   202.845900 -4.669248e-11  797.154100  1.685772  0.842886

[10000 rows x 5 columns]

In [77]:
data["recovered(O)"] = Df3["new"]

In [78]:
data["infected(O)"] = Df2["new"]

In [79]:
data["suspectible(O)"] = Df1["new"]

In [80]:
data

      suspectible      infected  ...   infected(O)  suspectible(O)
0      998.989148  1.005421e+00  ...  1.008142e+00      998.983699
1      990.323929  5.314727e+00  ...  1.201927e+01      976.685896
2      992.810810  4.081862e+00  ...  8.160254e+00      984.559547
3      992.973760  4.000970e+00  ...  7.922792e+00      985.041916
4      990.666976  5.144849e+00  ...  1.146269e+01      977.825571
...           ...           ...  ...           ...             ...
9995   202.845900 -3.636757e-10  ... -4.469822e-10      202.845900
9996   202.902783  8.330995e-02  ...  7.299593e-02      202.895739
9997   202.845900 -3.176822e-11  ... -3.059821e-11      202.845900
9998   204.245126  2.037921e+00  ...  1.847596e+00      204.113761
9999   202.845900 -4.669248e-11  ... -4.567956e-11      202.845900

[10000 rows x 8 columns]